name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]

jobs:
  INSTALL-DEPENDENCIES:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.13]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - uses: actions/cache@v2
      id: restore-cache
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
  
  BUILD:

    runs-on: ubuntu-20.04
    needs: [INSTALL-DEPENDENCIES]

    strategy:
      matrix:
        node-version: [16.13]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: restore-cache
      uses: ~/.npm
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
    - run: npm run build
    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: ./build

  UNIT-TEST:

    runs-on: ubuntu-20.04
    needs: [BUILD]

    strategy:
      matrix:
        node-version: [16.13]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run test