name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.13]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci

  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.13]

    steps:
    - run: npm run build


  test_unit: 

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.13]

    steps:
    - run: npm test
